name: Train on data change

on:
  push:
    branches: [main]

jobs:
  check-data:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: check
        run: |
          git diff --name-only HEAD~1 HEAD | grep dvc.lock \
            && echo "changed=true" >> $GITHUB_OUTPUT \
            || echo "changed=false" >> $GITHUB_OUTPUT

  train:
    needs: check-data
    if: needs.check-data.outputs.changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install dvc[s3]

#      - name: Pull data
#        run: dvc pull

      - name: Run pipeline
        run: dvc repro

      - name: Push artifacts
        run: |
          dvc push
          git add dvc.lock models/
          git commit -m "retrain model" || true
          git push
